server:
    port: 8080
    server:
        servlet:
            session:
                cookie:
                    http-only: true
                    secure: true

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: passwordsql101
        url: jdbc:mysql://localhost:3306/playaround
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    mail:
        host: smtp.gmail.com
        port: 587    
        username: paavangpt@gmail.com
        password: modvpbkdtumapfry
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
